### ISSUE TITLE
1.91 build

### ISSUE THREAD

**Issue by NoxInmortus** [maresb/docker-build-s3fs#8]
Hello there

Any chance to have the v1.91 build ?

Cheers

**Comment by maresb** [comment]
Hello again!!!

In the past months I've gained some experience with multiarch docker builds via GH Actions, so I think I can *finally* slay #5 if I find an hour or so.

As for 1.91, let me see if I can do a quick publish via my previous workflow for you.

**Comment by maresb** [comment]
Done! I didn't test it very thoroughly, so please let me know if you have any issues.

**Comment by NoxInmortus** [comment]
> In the past months I've gained some experience with multiarch docker builds via GH Actions, so I think I can _finally_ slay #5 if I find an hour or so.

Very nice ! :D 
Thanks for the build!

**Comment by NoxInmortus** [comment]
Hey @maresb 
```bash
dpkg -i s3fs_1.91+git-v1.91-3_amd64.deb 
dpkg-deb: error: 's3fs_1.91+git-v1.91-3_amd64.deb' is not a Debian format archive
dpkg: error processing archive s3fs_1.91+git-v1.91-3_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 s3fs_1.91+git-v1.91-3_amd64.deb
```

Am i missing something ? Long time I didnt use s3fs

**Comment by maresb** [comment]
Hi @NoxInmortus, strange, it works for me:

From the repository root,

```bash
docker run --rm -it -v $PWD:/docker-build-s3fs ubuntu:20.04
apt update && dpkg -i /docker-build-s3fs/builds/s3fs_1.91+git-v1.91-3_amd64.deb
DEBIAN_FRONTEND=noninteractive apt -f -y install && s3fs --version
```

I wonder if Git is mangling the file. I'll try the same procedure with a fresh clone...

**Comment by maresb** [comment]
Ya, prepending

```
cd /tmp && git clone git@github.com:maresb/docker-build-s3fs.git && cd docker-build-s3fs
```

it's still working for me. Is it possible that your download is corrupt for some reason? Could you verify the md5sum?

**Comment by NoxInmortus** [comment]
Just tried on two differents vm:
```
:~/git $ git clone https://github.com/maresb/docker-build-s3fs.git
Cloning into 'docker-build-s3fs'...
remote: Enumerating objects: 229, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 229 (delta 38), reused 31 (delta 26), pack-reused 171
Receiving objects: 100% (229/229), 164.00 KiB | 2.60 MiB/s, done.
Resolving deltas: 100% (133/133), done.

:~/git $ cd docker-build-s3fs/builds/

:~/git/docker-build-s3fs/builds (master u=) $ md5sum s3fs_1.91+git-v1.91-3_amd64.deb 
95d714f60e8d294ed23b097384dd3c54  s3fs_1.91+git-v1.91-3_amd64.deb
```
It does not seems to be the same as displayed in the README.

**Comment by maresb** [comment]
Very strange!

I'm getting the same md5sum from the readme.

```
/tmp $ md5sum docker-build-s3fs/builds/s3fs_1.91+git-v1.91
-3_amd64.deb
95192b8c47c931623eb1ce49282338eb  docker-build-s3fs/builds/s3fs_1.91+git-v1.91-3_amd64.deb
```

Could you possibly have some Git hook which is mangling the file? Which OS are you running?

**Comment by NoxInmortus** [comment]
Not at all, using classic Ubuntu 20.04, i'm wondering wtf is happening...

**Comment by NoxInmortus** [comment]
Guess i will just build

**Comment by maresb** [comment]
Weird!!!!!

Perhaps there's something up with Git LFS.

Try downloading from here: https://github.com/maresb/docker-build-s3fs/raw/master/builds/s3fs_1.91%2Bgit-v1.91-3_amd64.deb

**Comment by NoxInmortus** [comment]
Dude it worked.

I have no clue x)

**Comment by NoxInmortus** [comment]
I read your way to install it through mamba, but as a non-conda/mamba user, it just feel so much easier to just install a deb package...

Thanks for your time anyway

**Comment by maresb** [comment]
Haha, that's really weird. Please let me know if you figure out what was going wrong.

How large was the corrupt file? (When Git LFS fails, in place of the binary files you end up with short text files with a pointer to the download link.)

**Comment by NoxInmortus** [comment]
Oh I just found out. I was downloading the blob. So a faking html file.

Aaah ... :)

**Comment by maresb** [comment]
But doesn't that contradict https://github.com/maresb/docker-build-s3fs/issues/8#issuecomment-1137049790? There you checked a clone.

**Comment by NoxInmortus** [comment]
Indeed that was two separate tries.

```
$ git clone https://github.com/maresb/docker-build-s3fs/
Cloning into 'docker-build-s3fs'...
lremote: Enumerating objects: 229, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 229 (delta 38), reused 31 (delta 26), pack-reused 171
Receiving objects: 100% (229/229), 164.00 KiB | 3.64 MiB/s, done.
Resolving deltas: 100% (133/133), done.

$ cd docker-build-s3fs/builds/

$ du -hs s3fs_1.91+git-v1.91-3_amd64.deb 
4.0K    s3fs_1.91+git-v1.91-3_amd64.deb

$ cat s3fs_1.91+git-v1.91-3_amd64.deb 
version https://git-lfs.github.com/spec/v1
oid sha256:9eca7cb1e9bb08b8e3ae9b476287712a8293493630c76d9102c5ac0058b098c0
size 222340
```

Guess you learn everyday

**Comment by maresb** [comment]
@NoxInmortus, regarding conda-forge, I should mention that if you just want the binary, you can skip the whole mamba environment setup and run
```bash
curl -Ls https://anaconda.org/conda-forge/s3fs-fuse/1.91/download/linux-64/s3fs-fuse-1.91-h66f7299_0.tar.bz2 | tar -xvj --strip-components=1 bin/s3fs
```
which will create the `s3fs` binary in the current directory. (This is not a great solution since it will not take care of the dependencies!)

**Comment by maresb** [comment]
I documented my above comment more thoroughly under https://github.com/maresb/docker-build-s3fs/blob/master/README.md#alternatives
